/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using template emitter:
 *      SOM Emitter emitctm: 2.23.1.9
 */

#ifndef SOM_Module_vncv_Source
#define SOM_Module_vncv_Source
#endif
#define vncv_Class_Source
#define M_vncv_Class_Source

#include "vncv.ih"
#include "debug.h"


SOM_Scope void  SOMLINK VNCV_vncvInsertSettingsPages(vncv *somSelf, 
                                                     HWND hwndDlg)
{
//  vncvData   *somThis = vncvGetData( somSelf );
  HAB        hab = WinQueryAnchorBlock( hwndDlg );
  HMODULE    hMod = wpsutilGetModuleHandle();
  PAGEINFO   stPI = { 0 };
  CHAR       acName[128];

  stPI.cb                  = sizeof(PAGEINFO);
  stPI.usPageInsertFlags   = BKA_FIRST;
  stPI.resid               = wpsutilGetModuleHandle();
  stPI.pszName             = acName;
  stPI.pCreateParams       = (PVOID)somSelf;

  WinLoadString( hab, hMod, IDS_ENCODINGS, sizeof(acName), acName );
  stPI.usPageStyleFlags    = BKA_MAJOR | BKA_STATUSTEXTON;
  stPI.pfnwp               = nbPageEncodings;
  stPI.dlgid               = IDDLG_PAGE_ENCODINGS;
  _wpInsertSettingsPage( somSelf, hwndDlg, &stPI );

  WinLoadString( hab, hMod, IDS_SERVER, sizeof(acName), acName );
  stPI.usPageStyleFlags    = BKA_MAJOR | BKA_STATUSTEXTON;
  stPI.pfnwp               = nbPageServer;
  stPI.dlgid               = IDDLG_PAGE_SERVER;
  _wpInsertSettingsPage( somSelf, hwndDlg, &stPI );
/*  WinSendMsg( hwndDlg, BKM_SETSTATUSLINETEXT, MPFROMLONG( ulPageId ),
              MPFROMP( acPage ) );*/
}

SOM_Scope void  SOMLINK VNCV_vncvSetDynamicIcon(vncv *somSelf, 
                                                BOOL fEnable)
{
  vncvData   *somThis = vncvGetData(somSelf);

  if ( fEnable != _fDynamicIcon )
  {
    _fDynamicIcon = fEnable;

    if ( fEnable )
    {
      if ( _hwndWaitApp != NULLHANDLE )
      {
        debugCP( "Update screenshot (icon)" );
        WinSendMsg( _hwndWaitApp, WM_WA_UPDATEICON, 0, 0 );
      }
    }
    else
    {
      ICONINFO         stIconInfo;

      debugCP( "Set default icon" );
      memset( &stIconInfo, 0, sizeof(ICONINFO) );
      stIconInfo.cb = sizeof(ICONINFO);
      stIconInfo.fFormat = ICON_CLEAR;

      if ( !_wpSetIconData( somSelf, &stIconInfo ) )
        debugCP( "wpSetIconData() failed" );
    }
  }

  if ( _hwndNotebookServerPage != NULLHANDLE )
    WinSendMsg( _hwndNotebookServerPage, WM_NBSERVERPAGE_UPDDYNICONCB, 0, 0 );
}

SOM_Scope void  SOMLINK VNCV_wpInitData(vncv *somSelf)
{
  vncvData   *somThis = vncvGetData( somSelf );

  vncv_parent_WPAbstract_wpInitData( somSelf );
  debugInit();

  _ulWMVNCVNotify = WinAddAtom( WinQuerySystemAtomTable(),
                                VNCVI_ATOM_WMVNCVNOTIFY );

#ifdef DEBUG_CODE
  _pszHostDisplay  = strdup( "172.26.96.6" );
  _fRememberPswd   = TRUE;
#else
  _pszHostDisplay  = NULL;
  _fRememberPswd   = DEF_REMEMBER_PSWD;
#endif
  _ulAttempts      = DEF_ATTEMPTS;
  _fViewOnly       = DEF_VIEW_ONLY;
  _ulBPP           = DEF_BPP;
  _fShareDesktop   = DEF_SHARE_DESKTOP;
  _pszEncodings    = strdup( DEF_ENCODINGS );
  _ulCompressLevel = DEF_COMPRESS_LEVEL;
  _ulQualityLevel  = DEF_QUALITY_LEVEL;
  _acCharset[0]    = '\0';
  _fDynamicIcon    = TRUE;
}

SOM_Scope void  SOMLINK VNCV_wpUnInitData(vncv *somSelf)
{
  vncvData *somThis = vncvGetData( somSelf );

  startDestroy( somSelf );

  if ( _pszHostDisplay != NULL )
    free( _pszHostDisplay );

  if ( _pszEncodings != NULL )
    free( _pszEncodings );

  WinDeleteAtom( WinQuerySystemAtomTable(), _ulWMVNCVNotify );
  vncv_parent_WPAbstract_wpUnInitData( somSelf );
  debugDone();
}

SOM_Scope BOOL  SOMLINK VNCV_wpSaveState(vncv *somSelf)
{
  vncvData   *somThis = vncvGetData( somSelf );

  _wpSaveString( somSelf, somCN_vncv, SK_HOSTDISPLAY, _pszHostDisplay );
  _wpSaveLong( somSelf, somCN_vncv, SK_REMEMBERPSWD, _fRememberPswd );
  _wpSaveLong( somSelf, somCN_vncv, SK_ATTEMPTS, _ulAttempts );
  _wpSaveLong( somSelf, somCN_vncv, SK_VIEWONLY, _fViewOnly );
  _wpSaveLong( somSelf, somCN_vncv, SK_BPP, _ulBPP );
  _wpSaveLong( somSelf, somCN_vncv, SK_SHAREDESKTOP, _fShareDesktop );
  _wpSaveString( somSelf, somCN_vncv, SK_ENCODINGS, _pszEncodings );
  _wpSaveLong( somSelf, somCN_vncv, SK_COMPRESSLEVEL, _ulCompressLevel );
  _wpSaveLong( somSelf, somCN_vncv, SK_QUALITYLEVEL, _ulQualityLevel );
  _wpSaveString( somSelf, somCN_vncv, SK_CHARSET, _acCharset );
  _wpSaveLong( somSelf, somCN_vncv, SK_DYNAMICICON, _fDynamicIcon );

  return vncv_parent_WPAbstract_wpSaveState( somSelf );
}

SOM_Scope BOOL  SOMLINK VNCV_wpRestoreState(vncv *somSelf, ULONG ulReserved)
{
  vncvData   *somThis = vncvGetData( somSelf );
  PSZ        pszNew;
  ULONG      cbBuf;
  BOOL       fDynamicIcon = _fDynamicIcon;

  if ( wpsutilLoadStrNew( somSelf, somCN_vncv, SK_HOSTDISPLAY, &pszNew ) )
  {
    if ( _pszHostDisplay != NULL )
      free( _pszHostDisplay );
    _pszHostDisplay = pszNew;
  }

  _wpRestoreLong( somSelf, somCN_vncv, SK_REMEMBERPSWD, &_fRememberPswd );
  _wpRestoreLong( somSelf, somCN_vncv, SK_REMEMBERPSWD, &_fRememberPswd );
  _wpRestoreLong( somSelf, somCN_vncv, SK_ATTEMPTS, &_ulAttempts );
  _wpRestoreLong( somSelf, somCN_vncv, SK_VIEWONLY, &_fViewOnly );
  _wpRestoreLong( somSelf, somCN_vncv, SK_BPP, &_ulBPP );
  _wpRestoreLong( somSelf, somCN_vncv, SK_SHAREDESKTOP, &_fShareDesktop );

  if ( wpsutilLoadStrNew( somSelf, somCN_vncv, SK_ENCODINGS, &pszNew ) )
  {
    if ( _pszEncodings != NULL )
      free( _pszEncodings );
    _pszEncodings = pszNew;
  }

  _wpRestoreLong( somSelf, somCN_vncv, SK_COMPRESSLEVEL, &_ulCompressLevel );
  _wpRestoreLong( somSelf, somCN_vncv, SK_QUALITYLEVEL, &_ulQualityLevel );
  cbBuf = sizeof( _acCharset );
  _wpRestoreString( somSelf, somCN_vncv, SK_CHARSET, _acCharset, &cbBuf );

  if ( _wpRestoreLong( somSelf, somCN_vncv, SK_DYNAMICICON, &fDynamicIcon ) )
    _vncvSetDynamicIcon( somSelf, fDynamicIcon );

  return vncv_parent_WPAbstract_wpRestoreState( somSelf, ulReserved );
}

SOM_Scope BOOL  SOMLINK VNCV_wpAddSettingsPages(vncv *somSelf, 
                                                HWND hwndNotebook)
{
  BOOL       fRes = vncv_parent_WPAbstract_wpAddSettingsPages( somSelf, 
                                                               hwndNotebook );

  _vncvInsertSettingsPages( somSelf, hwndNotebook );

  return fRes;
}

SOM_Scope ULONG  SOMLINK VNCV_wpAddObjectWindowPage(vncv *somSelf, 
                                                    HWND hwndNotebook)
{
  return (vncv_parent_WPAbstract_wpAddObjectWindowPage(somSelf, 
                                                       hwndNotebook));
}

SOM_Scope BOOL  SOMLINK VNCV_wpSetup(vncv *somSelf, PSZ pszSetupString)
{
  vncvData   *somThis = vncvGetData( somSelf );
  PSZ        pszNew;
  ULONG      cbBuf;
  BOOL       fDynamicIcon = _fDynamicIcon;

  if ( !vncv_parent_WPAbstract_wpSetup( somSelf, pszSetupString ) )
    return FALSE;

  if ( wpsutilSetupStrNew( somSelf, pszSetupString, "HOST", &pszNew ) )
  {
    if ( _pszHostDisplay != NULL )
      free( _pszHostDisplay );
    _pszHostDisplay = pszNew;
  }

  wpsutilSetupReadBool( somSelf, pszSetupString, "REMEMBERPSWD",
                        &_fRememberPswd );
  wpsutilSetupReadULong( somSelf, pszSetupString, "ATTEMPTS", &_ulAttempts );
  wpsutilSetupReadBool( somSelf, pszSetupString, "VIEWONLY", &_fViewOnly );
  wpsutilSetupReadULong( somSelf, pszSetupString, "BPP", &_ulBPP );
  wpsutilSetupReadBool( somSelf, pszSetupString, "SHAREDESKTOP",
                        &_fShareDesktop );

  if ( wpsutilSetupStrNew( somSelf, pszSetupString, "ENCODINGS", &pszNew ) )
  {
    if ( _pszEncodings != NULL )
      free( _pszEncodings );
    _pszEncodings = pszNew;
  }

  wpsutilSetupReadULong( somSelf, pszSetupString, "COMPRESSLEVEL",
                         &_ulCompressLevel );
  wpsutilSetupReadULong( somSelf, pszSetupString, "QUALITYLEVEL",
                         &_ulCompressLevel );
  cbBuf = sizeof( _acCharset );
  _wpScanSetupString( somSelf, pszSetupString, "CHARSET", _acCharset, &cbBuf );

  if ( wpsutilSetupReadBool( somSelf, pszSetupString, "DYNAMICICON",
                             &fDynamicIcon ) )
    _vncvSetDynamicIcon( somSelf, fDynamicIcon );

  return TRUE;
}

SOM_Scope WPObject*  SOMLINK VNCV_wpCreateFromTemplate(vncv *somSelf, 
                                                       WPFolder* folder, 
                                                       BOOL fLock)
{
  return vncv_parent_WPAbstract_wpCreateFromTemplate( somSelf, folder, fLock );
}

SOM_Scope void  SOMLINK VNCV_wpCopiedFromTemplate(vncv *somSelf)
{
  // Open properties notebook on object creation from the template.
  VNCV_wpOpen( somSelf, NULLHANDLE, OPEN_SETTINGS, 0L );
  vncv_parent_WPAbstract_wpCopiedFromTemplate( somSelf );
}

SOM_Scope HWND  SOMLINK VNCV_wpOpen(vncv *somSelf, HWND hwndCnr, 
                                    ULONG ulView, ULONG param)
{
  vncvData   *somThis = vncvGetData( somSelf );
  HWND       hwnd = NULLHANDLE;

  switch( ulView )
  {
    case OPEN_VNCV:
      if ( _pszHostDisplay == NULL )
        hwnd = vncv_parent_WPAbstract_wpOpen( somSelf, hwndCnr, OPEN_SETTINGS,
                                              param );
      else
        // We cannot return real hwnd for VNC Viewer. Fake value HWND_DESKTOP
        // will be used ==> need to overwrite wpSwitchTo() for switches to
        // OPEN_VNCV view.
        hwnd = startViewer( somSelf, "M_vncv" ) ? HWND_DESKTOP : NULLHANDLE;
      break;

    default:
      hwnd = vncv_parent_WPAbstract_wpOpen( somSelf, hwndCnr, ulView, param );
      break;
  }

  return hwnd;
}

/*
 * Our wpOpen() does not returns real HWND of vncv's window. We have
 * only application handle of vncviewer.exe. We need overwrite
 * wpSwitchTo() to support our switching for OPEN_VNCV view.
 */

SOM_Scope BOOL  SOMLINK VNCV_wpSwitchTo(vncv *somSelf, ULONG View)
{
  if ( View == OPEN_VNCV )
    return startSwithTo( somSelf );

  return vncv_parent_WPAbstract_wpSwitchTo( somSelf, View );
}

SOM_Scope BOOL  SOMLINK VNCV_wpModifyPopupMenu(vncv *somSelf, 
                                               HWND hwndMenu, 
                                               HWND hwndCnr, 
                                               ULONG iPosition)
{
//    vncvData *somThis = vncvGetData( somSelf );
    vncvMethodDebug("vncv","VNCV_wpModifyPopupMenu");

    return (vncv_parent_WPAbstract_wpModifyPopupMenu(somSelf, 
                                                     hwndMenu, 
                                                     hwndCnr, 
                                                     iPosition));
}

SOM_Scope BOOL  SOMLINK VNCV_wpMenuItemSelected(vncv *somSelf, 
                                                HWND hwndFrame, 
                                                ULONG ulMenuId)
{
//    vncvData *somThis = vncvGetData( somSelf );
    vncvMethodDebug("vncv","VNCV_wpMenuItemSelected");

    return (vncv_parent_WPAbstract_wpMenuItemSelected(somSelf, 
                                                      hwndFrame, 
                                                      ulMenuId));
}

SOM_Scope BOOL  SOMLINK VNCV_wpSetIconData(vncv *somSelf, PICONINFO pIconInfo)
{
  vncvData   *somThis = vncvGetData( somSelf );

  if ( !_fSetDynamicIconTime )
  {
    debugCP( "Disable dynamic icon" );
    _fDynamicIcon = FALSE;

    if ( _hwndNotebookServerPage != NULLHANDLE )
      WinSendMsg( _hwndNotebookServerPage, WM_NBSERVERPAGE_UPDDYNICONCB, 0, 0 );
  }

  return vncv_parent_WPAbstract_wpSetIconData( somSelf, pIconInfo );
}

SOM_Scope BOOL  SOMLINK VNCV_wpSetIcon(vncv *somSelf, HPOINTER hptrNewIcon)
{
/*  vncvData   *somThis = vncvGetData( somSelf );

  if ( !_fSetDynamicIconTime )
  {
    debugCP( "Disable dynamic icon" );
    _fDynamicIcon = FALSE;

    if ( _hwndNotebookServerPage != NULLHANDLE )
      WinSendMsg( _hwndNotebookServerPage, WM_NBSERVERPAGE_UPDDYNICONCB, 0, 0 );
  }*/

  return vncv_parent_WPAbstract_wpSetIcon( somSelf, hptrNewIcon );
}


SOM_Scope void  SOMLINK MVNCV_wpclsInitData(M_vncv *somSelf)
{
  M_vncv_parent_M_WPAbstract_wpclsInitData( somSelf );
}

SOM_Scope void  SOMLINK MVNCV_wpclsUnInitData(M_vncv *somSelf)
{
  M_vncv_parent_M_WPAbstract_wpclsUnInitData( somSelf );
}

SOM_Scope ULONG  SOMLINK MVNCV_wpclsQueryIconData(M_vncv *somSelf, 
                                                  PICONINFO pIconInfo)
{
  // provide own icon for all object instances of this class
  if ( pIconInfo != NULL )
  {
    pIconInfo->fFormat = ICON_RESOURCE;
    pIconInfo->hmod    = wpsutilGetModuleHandle();
    pIconInfo->resid   = ID_ICON;
  }
  return sizeof(ICONINFO);
}

SOM_Scope PSZ  SOMLINK MVNCV_wpclsQueryTitle(M_vncv *somSelf)
{
  return "VNC Viewer";
}

SOM_Scope ULONG  SOMLINK MVNCV_wpclsQueryStyle(M_vncv *somSelf)
{
  return CLSSTYLE_NEVERPRINT;
}

SOM_Scope BOOL  SOMLINK MVNCV_wpclsCreateDefaultTemplates(M_vncv *somSelf, 
                                                          WPObject* Folder)
{
#ifdef DEBUG_FILE
  // TRUE - do not create template for the class.
  return TRUE;
#else
  return FALSE;
#endif
}

SOM_Scope ULONG  SOMLINK MVNCV_wpclsQueryDefaultView(M_vncv *somSelf)
{
  return OPEN_VNCV;
}

